name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on:
      ubuntu-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Start npm/platform tasks
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install and Test @capacitor/configure
        run: |
          cd packages/configure
          npm ci && npm run build && npm test

      - name: Install and Test @capacitor/project
        run: |
          cd packages/project
          npm ci && npm run build && npm test

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/configure/package.json

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/project/package.json
